

{
    "admissionregistration.k8s.io":[
       "v1",
       "v1beta1"
    ],
    "apiextensions.k8s.io":[
       "v1",
       "v1beta1"
    ],
    "apiregistration.k8s.io":[
       "v1",
       "v1beta1"
    ],
    "apps":[
       "v1"
    ],
    "authentication.k8s.io":[
       "v1",
       "v1beta1"
    ],
    "authorization.k8s.io":[
       "v1",
       "v1beta1"
    ],
    "autoscaling":[
       "v1",
       "v2beta2",
       "v2beta1"
    ],
    "batch":[
       "v1",
       "v1beta1",
       "v2alpha1"
    ],
    "certificates.k8s.io":[
       "v1",
       "v1beta1"
    ],
    "coordination.k8s.io":[
       "v1",
       "v1beta1"
    ],
    "core":[
       "v1"
    ],
    "discovery.k8s.io":[
       "v1beta1"
    ],
    "events.k8s.io":[
       "v1",
       "v1beta1"
    ],
    "extensions":[
       "v1beta1"
    ],
    "flowcontrol.apiserver.k8s.io":[
       "v1alpha1"
    ],
    "networking.k8s.io":[
       "v1",
       "v1beta1"
    ],
    "node.k8s.io":[
       "v1beta1",
       "v1alpha1"
    ],
    "policy":[
       "v1beta1"
    ],
    "rbac.authorization.k8s.io":[
       "v1",
       "v1beta1",
       "v1alpha1"
    ],
    "scheduling.k8s.io":[
       "v1",
       "v1beta1",
       "v1alpha1"
    ],
    "settings.k8s.io":[
       "v1alpha1"
    ],
    "storage.k8s.io":[
       "v1",
       "v1beta1",
       "v1alpha1"
    ]
 }